# config.yaml
model_config:
  embedding_size: 50
  hidden_layers: [100, 50]
  dropout_rate: 0.5
  learning_rate: 0.001

training_config:
  batch_size: 64
  num_epochs: 25

data_config:
  train_path: "../data/ml-100k/u1.base"
  test_path: "../data/ml-100k/u1.test"
